
const debuffFormula = {
  "stun-chance-atk": { str: 0.2, max: 0.6 },
  "stun-chance-res": { vit: 0.2, agi: 0.2, max: 1 },
  "fear-chance-atk": { dex: 0.3, max: 0.6 },
  "fear-chance-res": { int: 0.2, luk: 0.2, max: 1 },
  "sleep-chance-atk": { dex: 0.2, max: 0.6 },
  "sleep-chance-res": { int: 0.2, luk: 0.2, max: 1 },
  "freeze-chance-atk": { int: 0.2, max: 0.6 },
  "freeze-chance-res": { int: 0.2, dex: 0.2, max: 1 },
  "poison-chance-atk": { luk: 0.3, max: 0.8 },
  "poison-chance-res": { vit: 0.2, int: 0.2, max: 1 },
  "petrify-chance-atk": { int: 0.2, max: 0.6 },
  "petrify-chance-res": { int: 0.2, dex: 0.2, max: 1 },
  "silence-chance-atk": { dex: 0.2, max: 1 },
  "silence-chance-res": { vit: 0.2, str: 0.2, max: 1 },
  "snare-chance-atk": { agi: 0.2, max: 0.6 },
  "snare-chance-res": { vit: 0.2, str: 0.2, max: 1 },
  "curse-chance-atk": { str: 0.3, max: 0.6 },
  "curse-chance-res": { int: 0.3, dex: 0.3, max: 1 },
  "blind-chance-atk": { str: 0.3, max: 1 },
  "blind-chance-res": { int: 0.2, dex: 0.2, max: 1 },
  "burn-chance-atk": { int: 0.3, max: 0.8 },
  "burn-chance-res": { vit: 0.2, agi: 0.2, max: 1 },
  "bleed-chance-atk": { int: 0.3, max: 0.8 },
  "bleed-chance-res": { vit: 0.2, int: 0.2, max: 1 },
  

  "stun-duration-atk": { str: 0.3, max: 0.8 },
  "stun-duration-res": { vit: 0.4, max: 1 },
  "fear-duration-atk": { dex: 0.3, max: 0.8 },
  "fear-duration-res": { int: 0.4, max: 1 },
  "sleep-duration-atk": { dex: 0.3, max: 0.8 },
  "sleep-duration-res": { int: 0.4, max: 1 },
  "freeze-duration-atk": { int: 0.3, max: 0.8 },
  "freeze-duration-res": { int: 0.4, max: 1 },
  "poison-duration-atk": { luk: 0.2, max: 0.8 },
  "poison-duration-res": { vit: 0.4, max: 1 },
  "petrify-duration-atk": { int: 0.3, max: 0.8 },
  "petrify-duration-res": { int: 0.4, max: 1 },
  "silence-duration-atk": { dex: 0.3, max: 0.8 },
  "silence-duration-res": { vit: 0.4, max: 1 },
  "snare-duration-atk": { agi: 0.3, max: 0.8 },
  "snare-duration-res": { vit: 0.4, max: 1 },
  "curse-duration-atk": { str: 0.3, max: 0.8 },
  "curse-duration-res": { int: 0.4, max: 1 },
  "blind-duration-atk": { str: 0.3, max: 0.8 },
  "blind-duration-res": { int: 0.4, max: 1 },
  "burn-duration-atk": { int: 0.3, max: 0.8 },
  "burn-duration-res": { vit: 0.4, max: 1 },
  "bleed-duration-atk": { int: 0.3, max: 0.8 },
  "bleed-duration-res": { vit: 0.4, max: 1 }
};

export default debuffFormula;